services:
  accounts:
    image: "vaibhavtomar041/accounts-ms"
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m -XX:ActiveProcessorCount=1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    networks:
      - bankMs

  cards:
    image: "vaibhavtomar041/cards-ms"
    environment:
      JAVA_TOOL_OPTIONS: "-Xms128m -Xmx256m -XX:ActiveProcessorCount=1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    networks:
      - bankMs
networks:
  bankMs:
    driver: "bridge"